import { db } from "./db";
import { products, sectors, timelineEvents, jobs, users } from "@shared/schema";
import { sql, eq } from "drizzle-orm";
import { hashPassword } from "./auth";

export async function autoSeedIfEmpty() {
  try {
    const existingProducts = await db.select({ id: products.id }).from(products).limit(1);
    if (existingProducts.length > 0) {
      console.log("Database already has data, skipping auto-seed.");
      await runDataMigrations();
      await warmupDatabase();
      return;
    }
    console.log("Database is empty, running auto-seed...");
    await seedDatabase();
    console.log("Auto-seed complete.");
  } catch (error: any) {
    if (error.message?.includes("does not exist") || error.code === "42P01") {
      console.log("Tables do not exist yet, skipping auto-seed (run db:push first).");
    } else {
      console.error("Auto-seed error:", error);
    }
  }
}

async function runDataMigrations() {
  try {
    const bowden = await db.select({ slug: products.slug, images: products.images }).from(products).where(eq(products.slug, "bowdenkabel-custom"));
    if (bowden.length > 0 && bowden[0].images?.[0]?.includes(".svg")) {
      await db.update(products).set({ images: ["/catalog/bowdenkabel-op-maat.png"] }).where(eq(products.slug, "bowdenkabel-custom"));
      await db.update(products).set({ images: ["/catalog/gaskabel-op-maat.jpeg"] }).where(eq(products.slug, "throttle-cables"));
      console.log("Migration: Bowdenkabel images updated to real photos.");
    }
  } catch (e) {
    console.log("Data migration (bowden) skipped.");
  }

  try {
    const keywordMap: Record<string, string[]> = {
      "industrie": ["bowdenkabel", "staalkabel", "push-pull", "spankabel", "hijskabel"],
      "sport-recreatie": ["bowdenkabel", "remkabel", "gaskabel", "veiligheidskabel", "spankabel"],
      "verlichting-interieur": ["ophangkabel", "gripper", "looping", "ophangkit", "kabelgrijper", "plafond", "verlichting"],
      "landbouw": ["bowdenkabel", "trekkabel", "push-pull", "gaskabel"],
      "medisch": ["bowdenkabel", "veiligheidskabel", "push-pull", "remkabel"],
      "signalisatie-shopfitting": ["display", "ophangkabel", "kabelgrijper", "gripper", "signalisatie"],
      "automotive": ["bowdenkabel", "gaskabel", "remkabel", "veiligheidskabel", "throttle"],
      "veiligheid": ["veiligheidskabel", "kabelgrijper", "anti-val", "ophangkabel"],
      "bouw": ["bowdenkabel", "staalkabel", "spankabel", "balustrade", "trapleuning"],
    };
    for (const [slug, keywords] of Object.entries(keywordMap)) {
      const existing = await db.select({ id: sectors.id, keywords: sectors.keywords }).from(sectors).where(eq(sectors.slug, slug));
      if (existing.length > 0 && (!existing[0].keywords || existing[0].keywords.length === 0)) {
        await db.update(sectors).set({ keywords }).where(eq(sectors.slug, slug));
      }
    }
    console.log("Migration: Sector keywords populated.");
  } catch (e) {
    console.log("Data migration (sector keywords) skipped.");
  }

  try {
    const evt1986 = await db.select({ id: timelineEvents.id, title: timelineEvents.title }).from(timelineEvents).where(eq(timelineEvents.year, 1986));
    if (evt1986.length > 0 && evt1986[0].title.includes("Jagwire")) {
      await db.update(timelineEvents).set({
        title: "Oudenaarde wordt hoofdkwartier",
        description: "Het bedrijf verhuist naar Oudenaarde als nieuw hoofdkwartier om de groeiende activiteiten te ondersteunen.",
      }).where(eq(timelineEvents.year, 1986));

      await db.update(timelineEvents).set({
        title: "Uitbreiding met Jagwire",
        description: "Het productaanbod wordt uitgebreid met Jagwire producten, wat de positie in de fiets- en motorsector versterkt.",
      }).where(eq(timelineEvents.year, 1993));

      console.log("Migration: Timeline 1986↔1993 corrected.");
    }

    const evt2011 = await db.select({ id: timelineEvents.id, title: timelineEvents.title }).from(timelineEvents).where(eq(timelineEvents.year, 2011));
    if (evt2011.length > 0 && evt2011[0].title.includes("REVER")) {
      await db.update(timelineEvents).set({
        title: "Verhuizing naar Ronse & nieuwe productlijnen",
        description: "Het hoofdkwartier verhuist naar Ronse. Lancering van de Cycling en Quick Suspension (QS) productlijnen.",
      }).where(eq(timelineEvents.year, 2011));

      await db.update(timelineEvents).set({
        title: "Productgamma uitgebreid met REVER",
        description: "Het productgamma wordt verder uitgebreid met REVER, waardoor het aanbod diverser en sterker wordt.",
      }).where(eq(timelineEvents.year, 2015));

      console.log("Migration: Timeline 2011↔2015 corrected.");
    }
  } catch (e) {
    console.log("Data migration (timeline) skipped.");
  }
}

async function warmupDatabase() {
  try {
    await Promise.all([
      db.select({ id: products.id }).from(products).limit(1),
      db.select({ id: sectors.id }).from(sectors).limit(1),
      db.select({ id: jobs.id }).from(jobs).limit(1),
    ]);
    console.log("Database warmed up successfully.");
  } catch (e) {
    console.log("Database warmup skipped.");
  }
}

export async function seedDatabase() {
 await db.execute(sql`DELETE FROM ${products}`);
 await db.execute(sql`DELETE FROM ${sectors}`);
 await db.execute(sql`DELETE FROM ${timelineEvents}`);
 await db.execute(sql`DELETE FROM ${jobs}`);

 const existingAdmin = await db.select().from(users).where(sql`${users.username} = 'admin'`);
 if (existingAdmin.length === 0) {
   const hashedPw = await hashPassword("velda2025");
   await db.insert(users).values({ username: "admin", password: hashedPw, role: "admin" });
   console.log("Admin user created (admin / velda2025)");
 }

 console.log("Seeding database...");

 await db.insert(timelineEvents).values([
  { year: 1935, title: "Oprichting Velda Cable Technics", description: "Velda Cable Technics wordt opgericht als specialist in staalkabelassemblage voor de fiets- en motorindustrie." },
  { year: 1986, title: "Oudenaarde wordt hoofdkwartier", description: "Het bedrijf verhuist naar Oudenaarde als nieuw hoofdkwartier om de groeiende activiteiten te ondersteunen." },
  { year: 1993, title: "Uitbreiding met Jagwire", description: "Het productaanbod wordt uitgebreid met Jagwire producten, wat de positie in de fiets- en motorsector versterkt." },
  { year: 2009, title: "Overname door Nelson Vroman", description: "Nelson Vroman neemt het bedrijf over en brengt een nieuwe visie en dynamiek in de organisatie." },
  { year: 2011, title: "Verhuizing naar Ronse & nieuwe productlijnen", description: "Het hoofdkwartier verhuist naar Ronse. Lancering van de Cycling en Quick Suspension (QS) productlijnen." },
  { year: 2015, title: "Productgamma uitgebreid met REVER", description: "Het productgamma wordt verder uitgebreid met REVER, waardoor het aanbod diverser en sterker wordt." },
  { year: 2024, title: "LTWOO toegevoegd aan het assortiment", description: "LTWOO wordt toegevoegd aan het productaanbod, wat de positie in de fietsindustrie verder versterkt." },
 ]);

 const allProducts: any[] = [];

 // ========== PRODUCTS FROM WIREROPEMATE.COM (75 products) ==========
 allProducts.push({"slug":"draaibare-kabelgrijper","name":"Draaibare Kabelgrijper","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/staal"],"descriptionShort":"Kabelgrijper voor kabels 1.5-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.5-2.0mm. Breekbelasting 80-120kg, werkbelasting 16-24kg. Afmeting: 42x30x5.9mm. Materiaal: Brass/Steel. Kabeluitgang: Onderuitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.5-2.0mm","Breekbelasting":"80-120kg","Werkbelasting":"16-24kg","Afmeting":"42x30x5.9mm","Materiaal":"Messing/Staal","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/rotational-cable-gripper.jpg","/catalog/cable-gripper/rotational-cable-gripper-2.jpg"],"documents":[]});
 allProducts.push({"slug":"kabelgrijper-met-m8-schroefdraad","name":"Kabelgrijper met M8 Schroefdraad","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.0-1.2mm, werkbelasting 6-8kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.0-1.2mm. Breekbelasting 30-40kg, werkbelasting 6-8kg. Afmeting: 11.5xM8x1.0mm. Materiaal: Brass/Alu. Kabeluitgang: Onderuitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.0-1.2mm","Breekbelasting":"30-40kg","Werkbelasting":"6-8kg","Afmeting":"11.5xM8x1.0mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/cable-gripper-by-thread-m8.jpg","/catalog/cable-gripper/cable-gripper-by-thread-m8-2.jpg"],"documents":[]});
 allProducts.push({"slug":"vierkante-kabelgrijper","name":"Vierkante Kabelgrijper","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.5-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.5-2.0mm. Breekbelasting 80-120kg, werkbelasting 16-24kg. Afmeting: 32.5x10x6.25mm. Materiaal: Brass/Alu. Kabeluitgang: Onderuitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.5-2.0mm","Breekbelasting":"80-120kg","Werkbelasting":"16-24kg","Afmeting":"32.5x10x6.25mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/square-cable-gripper.jpg","/catalog/cable-gripper/square-cable-gripper-2.jpg"],"documents":[]});
 allProducts.push({"slug":"kabelgrijper-met-buitendraad","name":"Kabelgrijper met Buitendraad","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.5-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.5-2.0mm. Breekbelasting 80-120kg, werkbelasting 16-24kg. Afmeting: 39xM10x1.0mm. Materiaal: Brass/Alu. Kabeluitgang: Zij-uitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.5-2.0mm","Breekbelasting":"80-120kg","Werkbelasting":"16-24kg","Afmeting":"39xM10x1.0mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Zij-uitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/cable-gripper-with-male-thread.jpg","/catalog/cable-gripper/cable-gripper-with-male-thread-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaibare-kabelgrijper-met-schroef","name":"Draaibare Kabelgrijper met Schroef","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.8-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.8-2.0mm. Breekbelasting 80-120kg, werkbelasting 16-24kg. Afmeting: 34.5xM6x1.0mm. Materiaal: Brass/Alu. Kabeluitgang: Beide zijden. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.8-2.0mm","Breekbelasting":"80-120kg","Werkbelasting":"16-24kg","Afmeting":"34.5xM6x1.0mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/rotational-cable-gripper-with-screw.jpg","/catalog/cable-gripper/rotational-cable-gripper-with-screw-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaibare-kabelgrijper-zij-uitgang","name":"Draaibare Kabelgrijper Zij-uitgang","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.5-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.5-2.0mm. Breekbelasting 80-160kg, werkbelasting 16-24kg. Afmeting: 34.5x10x4.9mm. Materiaal: Brass/Alu. Kabeluitgang: Beide zijden. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.5-2.0mm","Breekbelasting":"80-160kg","Werkbelasting":"16-24kg","Afmeting":"34.5x10x4.9mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/rotational-cable-gripper-side-exit.jpg","/catalog/cable-gripper/rotational-cable-gripper-side-exit-2.jpg"],"documents":[]});
 allProducts.push({"slug":"haak-kabelgrijper-zij-uitgang","name":"Haak Kabelgrijper Zij-uitgang","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.2-1.5mm, werkbelasting 8-16kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.2-1.5mm. Breekbelasting 40-80kg, werkbelasting 8-16kg. Afmeting: 18x26x3.9mm. Materiaal: Brass/Alu. Kabeluitgang: Zij-uitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"40-80kg","Werkbelasting":"8-16kg","Afmeting":"18x26x3.9mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Zij-uitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/hook-cable-gripper-side-exit.jpg","/catalog/cable-gripper/hook-cable-gripper-side-exit-2.jpg"],"documents":[]});
 allProducts.push({"slug":"haak-kabelgrijper","name":"Haak Kabelgrijper","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.2-1.5mm, werkbelasting 8-16kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.2-1.5mm. Breekbelasting 40-80kg, werkbelasting 8-16kg. Afmeting: 36x10x3.9mm. Materiaal: Brass/Alu. Kabeluitgang: Beide zijden. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"40-80kg","Werkbelasting":"8-16kg","Afmeting":"36x10x3.9mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/hook-cable-gripper.jpg","/catalog/cable-gripper/hook-cable-gripper-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafond-kabelgrijper","name":"Plafond Kabelgrijper","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/staal"],"descriptionShort":"Kabelgrijper voor kabels 1.5-2.0mm, werkbelasting 16-24kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.5-2.0mm. Breekbelasting 80-120kg, werkbelasting 16-24kg. Afmeting: 40x25.5x12mm. Materiaal: Brass/Steel. Kabeluitgang: Onderuitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.5-2.0mm","Breekbelasting":"80-120kg","Werkbelasting":"16-24kg","Afmeting":"40x25.5x12mm","Materiaal":"Messing/Staal","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/ceiling-cable-gripper.jpg","/catalog/cable-gripper/ceiling-cable-gripper-2.jpg"],"documents":[]});
 allProducts.push({"slug":"kabelgrijper-met-gekarteld-oppervlak","name":"Kabelgrijper met Gekarteld Oppervlak","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.2-1.5mm, werkbelasting 8-16kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.2-1.5mm. Breekbelasting 40-80kg, werkbelasting 8-16kg. Afmeting: 27x10x3.9mm. Materiaal: Brass/Alu. Kabeluitgang: Beide zijden. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"40-80kg","Werkbelasting":"8-16kg","Afmeting":"27x10x3.9mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/cable-grippers-by-knurled-surface.jpg","/catalog/cable-gripper/cable-grippers-by-knurled-surface-2.jpg"],"documents":[]});
 allProducts.push({"slug":"kabelgrijper-cg033","name":"Kabelgrijper CG033","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.2-1.5mm, werkbelasting 8-16kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.2-1.5mm. Breekbelasting 40-80kg, werkbelasting 8-16kg. Afmeting: 18xM5x0.7mm. Materiaal: Brass/Alu. Kabeluitgang: Zij-uitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"40-80kg","Werkbelasting":"8-16kg","Afmeting":"18xM5x0.7mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Zij-uitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/cable-gripper-cg033.jpg","/catalog/cable-gripper/cable-gripper-cg033-2.jpg"],"documents":[]});
 allProducts.push({"slug":"kabelgrijper-zij-uitgang","name":"Kabelgrijper Zij-uitgang","type":"Gripper","category":"Cable Gripper","tags":["cable gripper","messing/aluminium"],"descriptionShort":"Kabelgrijper voor kabels 1.2-1.5mm, werkbelasting 8-16kg.","descriptionLong":"Hoogwaardige kabelgrijper geschikt voor staalkabels van 1.2-1.5mm. Breekbelasting 40-80kg, werkbelasting 8-16kg. Afmeting: 37xM10x1.0mm. Materiaal: Brass/Alu. Kabeluitgang: Zij-uitgang. Geschikt voor 7x7 or 7x19 kabelconstructies.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"40-80kg","Werkbelasting":"8-16kg","Afmeting":"37xM10x1.0mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Zij-uitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/cable-gripper/cable-gripper-by-side-exit.jpg","/catalog/cable-gripper/cable-gripper-by-side-exit-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-lg-002zn","name":"Looping Gripper LG-002ZN","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 3.5-4.0-5.0mm. Materiaal: Brass/Alu. Breekbelasting: 12.5-50kg.","specs":{"Kabeldiameter":"3.5-4.0-5.0mm","Breekbelasting":"12.5-50kg","Werkbelasting":"450-500-600kg","Afmeting":"42x44x25mm","Materiaal":"Messing/Aluminium","Afwerking":"Zinc","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/27.jpg","/catalog/looping-gripper/27-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-lg-001zn","name":"Looping Gripper LG-001ZN","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 1.0-1.5mm. Materiaal: Brass/Alu. Breekbelasting: 80-130kg.","specs":{"Kabeldiameter":"1.0-1.5mm","Breekbelasting":"80-130kg","Werkbelasting":"16-26kg","Afmeting":"20x20x10mm","Materiaal":"Messing/Aluminium","Afwerking":"Zinc","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/26.jpg","/catalog/looping-gripper/26-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-42mm","name":"Looping Gripper 42mm","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 3.5-4.0-5.0mm. Materiaal: Brass/Alu. Breekbelasting: 450-500-600kg.","specs":{"Kabeldiameter":"3.5-4.0-5.0mm","Breekbelasting":"450-500-600kg","Werkbelasting":"90-120kg","Afmeting":"42x42x22mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/25.jpg","/catalog/looping-gripper/25-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-30mm","name":"Looping Gripper 30mm","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 2.5-3.0mm. Materiaal: Brass/Alu. Breekbelasting: 300-400kg.","specs":{"Kabeldiameter":"2.5-3.0mm","Breekbelasting":"300-400kg","Werkbelasting":"60-80kg","Afmeting":"30x30x15mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/24.jpg","/catalog/looping-gripper/24-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-20mm","name":"Looping Gripper 20mm","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 1.2-1.5mm. Materiaal: Brass/Alu. Breekbelasting: 80-130kg.","specs":{"Kabeldiameter":"1.2-1.5mm","Breekbelasting":"80-130kg","Werkbelasting":"16-26kg","Afmeting":"20x18x10mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/cable-holder-looping-gripper-20mm.jpg","/catalog/looping-gripper/cable-holder-looping-gripper-20mm-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-25mm","name":"Looping Gripper 25mm","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 1.8-2.0mm. Materiaal: Brass/Alu. Breekbelasting: 180-200kg.","specs":{"Kabeldiameter":"1.8-2.0mm","Breekbelasting":"180-200kg","Werkbelasting":"36-40kg","Afmeting":"15x15x8.5mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/cable-fixer-looping-gripper-25mm.jpg","/catalog/looping-gripper/cable-fixer-looping-gripper-25mm-2.jpg"],"documents":[]});
 allProducts.push({"slug":"looping-gripper-15mm","name":"Looping Gripper 15mm","type":"Gripper","category":"Looping Gripper","tags":["looping gripper","messing/aluminium"],"descriptionShort":"Looping gripper voor eenvoudige hoogteverstelling van ophangkabels.","descriptionLong":"Universele looping gripper voor snelle en gereedschapsloze hoogteverstelling. Geschikt voor kabels van 0.8-1.0mm. Materiaal: Brass/Alu. Breekbelasting: 12.5-50kg.","specs":{"Kabeldiameter":"0.8-1.0mm","Breekbelasting":"12.5-50kg","Werkbelasting":"2.5-10kg","Afmeting":"15x15x8.5mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Beide zijden","Kabelconstructie":"7x7 or 7x19","Toepassing":"Ophangingssysteem"},"images":["/catalog/looping-gripper/lopping_gripper_15mm.jpg","/catalog/looping-gripper/lopping_gripper_15mm-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaischijf-met-buitendraad","name":"Draaischijf met Buitendraad","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 23x16xM10x1.0mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M10x1.0mm","Draaihoek":"Vertical:60&deg;","Afmeting":"23x16xM10x1.0mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/swivel-joint-with-male-thread.jpg","/catalog/swivel-joint/swivel-joint-with-male-thread-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaischijf-m10-1-0","name":"Draaischijf M10×1.0","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 32xM10x1.0mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M10x1.0mm","Draaihoek":"Horizontal:330&deg;/Vertical:90&deg;","Afmeting":"32xM10x1.0mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/swivel-joits-thread-m10x1-0.jpg","/catalog/swivel-joint/swivel-joits-thread-m10x1-0-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaischijf-90-sj049","name":"Draaischijf 90° SJ049","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 33.5x10.5xM8x1.0mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M8x1.0mm","Draaihoek":"Horizontal:330&deg;/Vertical:90&deg;","Afmeting":"33.5x10.5xM8x1.0mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/swivel-joits-90-degrees.jpg","/catalog/swivel-joint/swivel-joits-90-degrees-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaischijf-met-klemmoer","name":"Draaischijf met Klemmoer","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 30x12x12mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M10x1.0mm","Draaihoek":"Vertical:90&deg;","Afmeting":"30x12x12mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/wring-nut-swivel-joint.jpg","/catalog/swivel-joint/wring-nut-swivel-joint-2.jpg"],"documents":[]});
 allProducts.push({"slug":"draaischijf-dubbele-schroefdraad","name":"Draaischijf Dubbele Schroefdraad","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 23xM8x1.0mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M8x1.0mm","Draaihoek":"Horizontal:330&deg;/Vertical:90&deg;","Afmeting":"23xM8x1.0mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/swivel-joits-both-thread.jpg","/catalog/swivel-joint/swivel-joits-both-thread-2.jpg"],"documents":[]});
 allProducts.push({"slug":"voet-draaischijf","name":"Voet Draaischijf","type":"Joint","category":"Swivel Joint","tags":["swivel joint","brass"],"descriptionShort":"Draaischijf voor flexibele verbindingen in kabelsystemen.","descriptionLong":"Precisie draaischijf voor roterende verbindingen. Afmeting: 28.5x33x13mm. Materiaal: Brass. Afwerking: Silver.","specs":{"Materiaal":"Brass","Draadmaat":"M10x1.0mm","Draaihoek":"Horizontal:330&deg;/Vertical:180&deg;","Afmeting":"28.5x33x13mm","Afwerking":"Zilver","Toepassing":"Verlichtingsarmatuur"},"images":["/catalog/swivel-joint/pedestal-swivel-joint.jpg","/catalog/swivel-joint/pedestal-swivel-joint-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-t-profiel-ca028","name":"Plafondbevestiging T-Profiel CA028","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","staal"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Steel. Afwerking: White/Zinc. Afmeting: 40.5x22.5x1mm.","specs":{"Werkbelasting":"8kg","Afmeting":"40.5x22.5x1mm","Materiaal":"Staal","Afwerking":"Wit/Zink","Installatie":"Twist On","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-t-bar-ca028.jpg","/catalog/ceiling-attachment/ceiling-attachments-t-bar-ca028-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-railklem-ca032","name":"Plafondbevestiging Railklem CA032","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","staal"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Steel. Afwerking: White/Zinc. Afmeting: 36x30x13mm.","specs":{"Werkbelasting":"8kg","Afmeting":"36x30x13mm","Materiaal":"Staal","Afwerking":"Wit/Zink","Installatie":"Twist On","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca032.jpg","/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca032-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-railklem-ca033","name":"Plafondbevestiging Railklem CA033","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","staal"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Steel. Afwerking: White/Zinc. Afmeting: 35x34x16mm.","specs":{"Werkbelasting":"8kg","Afmeting":"35x34x16mm","Materiaal":"Staal","Afwerking":"Wit/Zink","Installatie":"Twist On","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca033.jpg","/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca033-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-railklem-ca035","name":"Plafondbevestiging Railklem CA035","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","staal"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Steel. Afwerking: White/Zinc. Afmeting: 14x31xM6x1.0mm.","specs":{"Werkbelasting":"8kg","Afmeting":"14x31xM6x1.0mm","Materiaal":"Staal","Afwerking":"Wit/Zink","Installatie":"Twist On","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca035.jpg","/catalog/ceiling-attachment/ceiling-attachments-track-clip-ca035-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-t-profiel-ca027","name":"Plafondbevestiging T-Profiel CA027","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","staal"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Steel. Afwerking: White/Zinc. Afmeting: 38.5x28.7x1mm.","specs":{"Werkbelasting":"8kg","Afmeting":"38.5x28.7x1mm","Materiaal":"Staal","Afwerking":"Wit/Zink","Installatie":"Twist On","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-t-bar-ca027.jpg","/catalog/ceiling-attachment/ceiling-attachments-t-bar-ca027-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafondbevestiging-ca026","name":"Plafondbevestiging CA026","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 20x73mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"20x73mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-ca026.jpg","/catalog/ceiling-attachment/ceiling-attachments-ca026-2.jpg"],"documents":[]});
 allProducts.push({"slug":"conische-plafondbevestiging-ca023","name":"Conische Plafondbevestiging CA023","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 20x27mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"20x27mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/cone-ceiling-attachments-ca023.jpg","/catalog/ceiling-attachment/cone-ceiling-attachments-ca023-2.jpg"],"documents":[]});
 allProducts.push({"slug":"magnetic-ceiling-attachments-ca022","name":"Magnetic Ceiling attachments CA022","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 32x13mm.","specs":{"Kabeldiameter":"1.5mm","Afmeting":"32x13mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/magnetic-ceiling-attachments-ca022.jpg","/catalog/ceiling-attachment/magnetic-ceiling-attachments-ca022-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ceiling-attachments-ca021","name":"Ceiling attachments CA021","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 18x32mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"18x32mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-ca021.jpg","/catalog/ceiling-attachment/ceiling-attachments-ca021-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ceiling-attachments-ca020","name":"Ceiling attachments CA020","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 115x25mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"115x25mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-ca020.jpg","/catalog/ceiling-attachment/ceiling-attachments-ca020-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ceiling-attachments-ca019","name":"Ceiling attachments CA019","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 20x23x16mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"20x23x16mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-ca019.jpg","/catalog/ceiling-attachment/ceiling-attachments-ca019-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ceiling-attachments-ca018","name":"Ceiling attachments CA018","type":"Attachment","category":"Plafondbevestiging","tags":["plafondbevestiging","messing/aluminium"],"descriptionShort":"Plafondbevestiging voor professionele ophangingssystemen.","descriptionLong":"Betrouwbare plafondbevestiging voor verlichting, signalisatie en displays. Materiaal: Brass/Alu. Afwerking: Nickel. Afmeting: 20x22x16mm.","specs":{"Kabeldiameter":"1.5mm","Breekbelasting":"150kg","Afmeting":"20x22x16mm","Materiaal":"Messing/Aluminium","Afwerking":"Vernikkeld","Kabeluitgang":"Onderuitgang","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/ceiling-attachment/ceiling-attachments-ca018.jpg","/catalog/ceiling-attachment/ceiling-attachments-ca018-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-lus-en-oog-wr056","name":"Staalkabel met Lus en Oog WR056","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.5mm","Breekbelasting":"150kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/loop-and-eye-end-wire-rope-wr056.jpg","/catalog/wire-ropes/loop-and-eye-end-wire-rope-wr056-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-lus-en-karabijnhaak-wr060","name":"Staalkabel met Lus en Karabijnhaak WR060","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.2mm","Breekbelasting":"100kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/loop-end-wire-rope-with-climbing-snap-ho.jpg","/catalog/wire-ropes/loop-end-wire-rope-with-climbing-snap-ho-2.jpg"],"documents":[]});
 allProducts.push({"slug":"rvs-staalkabel-met-lus-wr059","name":"RVS Staalkabel met Lus WR059","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.0mm","Breekbelasting":"65kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/loop-end-stainless-steel-wire-rope-wr059.jpg","/catalog/wire-ropes/loop-end-stainless-steel-wire-rope-wr059-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-lus-en-oog-wr058","name":"Staalkabel met Lus en Oog WR058","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.2mm","Breekbelasting":"100kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/wire-rope-with-loop-and-eye-end-wr058.jpg","/catalog/wire-ropes/wire-rope-with-loop-and-eye-end-wr058-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-dubbele-lus-wr057","name":"Staalkabel Dubbele Lus WR057","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"2.0mm","Breekbelasting":"265kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/double-loop-end-wire-rope-wr057.jpg","/catalog/wire-ropes/double-loop-end-wire-rope-wr057-2.jpg"],"documents":[]});
 allProducts.push({"slug":"gegalvaniseerde-staalkabel-t-en-oog-einde-wr055","name":"Gegalvaniseerde Staalkabel T- en Oog-einde WR055","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.5mm","Breekbelasting":"150kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/galvanized-wire-rope-with-t-and-eye-end-.jpg","/catalog/wire-ropes/galvanized-wire-rope-with-t-and-eye-end--2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-paddenstoeleinde-wr054","name":"Staalkabel met Paddenstoeleinde WR054","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.5mm","Breekbelasting":"150kg","Length of Wire Rope":"2M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/diecast-mushroom-end-wire-rope-wr054.jpg","/catalog/wire-ropes/diecast-mushroom-end-wire-rope-wr054-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-t-en-oog-einde-wr053","name":"Staalkabel met T- en Oog-einde WR053","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.5mm","Breekbelasting":"150kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/wire-rope-with-end-by-t-and-eye-wr053.jpg","/catalog/wire-ropes/wire-rope-with-end-by-t-and-eye-wr053-2.jpg"],"documents":[]});
 allProducts.push({"slug":"rvs-staalkabel-met-oog-en-paddenstoeleinde-wr052","name":"RVS Staalkabel met Oog en Paddenstoeleinde WR052","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.5mm","Breekbelasting":"150kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/stainless-steel-wire-rope-with-eye-and-d.jpg","/catalog/wire-ropes/stainless-steel-wire-rope-with-eye-and-d-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-ring-ogen-wr051","name":"Staalkabel met Ring-ogen WR051","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.0mm","Breekbelasting":"65kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/ring-eyes-wire-rope-wr051.jpg","/catalog/wire-ropes/ring-eyes-wire-rope-wr051-2.jpg"],"documents":[]});
 allProducts.push({"slug":"staalkabel-met-terminal-ogen-wr050","name":"Staalkabel met Terminal-ogen WR050","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.2mm","Breekbelasting":"100kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/terminal-wire-rope-with-eyes-wr050.jpg","/catalog/wire-ropes/terminal-wire-rope-with-eyes-wr050-2.jpg"],"documents":[]});
 allProducts.push({"slug":"wire-rope-with-ring-eyes-wr049","name":"Wire Rope With Ring-eyes WR049","type":"Cable","category":"Staalkabels","tags":["staalkabels","stainless steel"],"descriptionShort":"Staalkabel met professionele eindafwerking.","descriptionLong":"Hoogwaardige staalkabel met fabrieksmatige eindafwerking. Materiaal: Stainless Steel. Beschikbaar in diverse lengtes.","specs":{"Diameter of Wire Rope":"1.0mm","Breekbelasting":"65kg","Length of Wire Rope":"4M or as requirement","Materiaal":"Stainless Steel","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"Light/Lamp Fixture"},"images":["/catalog/wire-ropes/wire-rope-with-ring-eyes-wr049.jpg","/catalog/wire-ropes/wire-rope-with-ring-eyes-wr049-2.jpg"],"documents":[]});
 allProducts.push({"slug":"verlichtings-ophangkit-sk053","name":"Verlichtings-ophangkit SK053","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"1500mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/lighting-suspension-kit-sk053.jpg","/catalog/suspension-kits/lighting-suspension-kit-sk053-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ophangkit-sk056","name":"Ophangkit SK056","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"2000mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/suspension-kit-sk056.jpg","/catalog/suspension-kits/suspension-kit-sk056-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ophangkit-sk051","name":"Ophangkit SK051","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"1500mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/suspension-kit-sk051.jpg","/catalog/suspension-kits/suspension-kit-sk051-2.jpg"],"documents":[]});
 allProducts.push({"slug":"zwarte-plafond-ophangkit-sk060","name":"Zwarte Plafond-ophangkit SK060","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.5mm","Length of Wire Rope":"1000mm","Breekbelasting":"150kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/black-ceiling-suspension-kit-sk060.jpg","/catalog/suspension-kits/black-ceiling-suspension-kit-sk060-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ophangkit-sk058","name":"Ophangkit SK058","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"2000mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/suspension-kit-sk058.jpg","/catalog/suspension-kits/suspension-kit-sk058-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ophangkit-sk057","name":"Ophangkit SK057","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"1050mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/suspension-kit-sk057.jpg","/catalog/suspension-kits/suspension-kit-sk057-2.jpg"],"documents":[]});
 allProducts.push({"slug":"haak-ophangkit-sk055","name":"Haak-ophangkit SK055","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"2000mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/hook-suspension-kit-sk055.jpg","/catalog/suspension-kits/hook-suspension-kit-sk055-2.jpg"],"documents":[]});
 allProducts.push({"slug":"ophangkit-sk054","name":"Ophangkit SK054","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.0mm","Length of Wire Rope":"1200mm","Breekbelasting":"65kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/suspension-kits-sk054.jpg","/catalog/suspension-kits/suspension-kits-sk054-2.jpg"],"documents":[]});
 allProducts.push({"slug":"plafond-ophangkit-sk052","name":"Plafond-ophangkit SK052","type":"Kit","category":"Ophangkits","tags":["ophangkits","galvanized or stainless steel"],"descriptionShort":"Complete ophangkit voor verlichting en displays.","descriptionLong":"Kant-en-klare ophangkit inclusief staalkabel, kabelgrijper en plafondbevestiging. Materiaal: Galvanized or stainless steel. Afwerking: Galvanized. ","specs":{"Diameter of Wire Rope":"1.2mm","Length of Wire Rope":"2200mm","Breekbelasting":"95kg","End of fittings":"Cable gripper,metal fittings","Materiaal":"Gegalvaniseerd of roestvast staal","Afwerking":"Gegalvaniseerd","Kabelconstructie":"7x7 or 7x19","Toepassing":"It can be used to hang lights, clotheslines, pictures, patio sunshade, and so on."},"images":["/catalog/suspension-kits/ceiling-suspension-kits-sk052.jpg","/catalog/suspension-kits/ceiling-suspension-kits-sk052-2.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds021","name":"Display Accessoire DS021","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds021.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds020","name":"Display Accessoire DS020","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds020.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds019","name":"Display Accessoire DS019","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds019.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds018","name":"Display Accessoire DS018","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds018.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds017","name":"Display Accessoire DS017","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds017.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds016","name":"Display Accessoire DS016","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds016.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds015","name":"Display Accessoire DS015","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds015.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds014","name":"Display Accessoire DS014","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds014.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds013","name":"Display Accessoire DS013","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds013.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds012","name":"Display Accessoire DS012","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds012.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds011","name":"Display Accessoire DS011","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds011.jpg"],"documents":[]});
 allProducts.push({"slug":"display-accessoire-ds009","name":"Display Accessoire DS009","type":"Accessory","category":"Display Systeem","tags":["display systeem"],"descriptionShort":"Display accessoire voor professionele presentatiesystemen.","descriptionLong":"Hoogwaardig display accessoire voor winkelinrichtingen, tentoonstellingen en showrooms. Materiaal: -. ","specs":{"Kleur":"Zilver","Finish":"Satin chrome-plated","Toepassing":"Display stand"},"images":["/catalog/display/display-accessories-ds009.jpg"],"documents":[]});
 allProducts.push({"slug":"gietstukken-op-maat","name":"Gietstukken op Maat","type":"Accessory","category":"CNC, Draaien en Gieten","tags":["CNC","gieten","draaien"],"descriptionShort":"CNC precisie-onderdeel voor verlichtingsarmaturen.","descriptionLong":"CNC precisie-onderdeel voor verlichtingsarmaturen. ","specs":{},"images":["/catalog/precision-metal/112.png","/catalog/precision-metal/112-2.png","/catalog/precision-metal/112-3.png","/catalog/precision-metal/112-4.png","/catalog/precision-metal/112-5.png","/catalog/precision-metal/112-6.png"],"documents":[]});
 allProducts.push({"slug":"bevestiger-ra005","name":"Bevestiger RA005","type":"Accessory","category":"CNC, Draaien en Gieten","tags":["CNC","draaien","bevestiger"],"descriptionShort":"CNC precisie-onderdeel voor verlichtingsarmaturen.","descriptionLong":"CNC precisie-onderdeel voor verlichtingsarmaturen. Toepassing: Lighting installation related accessories.","specs":{"Kleur":"Geel","Finish":"Satin chrome-plated","Toepassing":"Verlichtingsarmatuur accessoires"},"images":["/catalog/precision-metal/fastener-ra005.jpg"],"documents":[]});
 allProducts.push({"slug":"bevestiger-ra003","name":"Bevestiger RA003","type":"Accessory","category":"CNC, Draaien en Gieten","tags":["CNC","draaien","bevestiger"],"descriptionShort":"CNC precisie-onderdeel voor verlichtingsarmaturen.","descriptionLong":"CNC precisie-onderdeel voor verlichtingsarmaturen. Toepassing: Lighting installation related accessories.","specs":{"Kleur":"Geel","Finish":"Satin chrome-plated","Toepassing":"Verlichtingsarmatuur accessoires"},"images":["/catalog/precision-metal/fastener-ra003.jpg"],"documents":[]});
 allProducts.push({"slug":"bevestiger-ra002","name":"Bevestiger RA002","type":"Accessory","category":"CNC, Draaien en Gieten","tags":["CNC","draaien","bevestiger"],"descriptionShort":"CNC precisie-onderdeel voor verlichtingsarmaturen.","descriptionLong":"CNC precisie-onderdeel voor verlichtingsarmaturen. Toepassing: Lighting installation related accessories.","specs":{"Kleur":"Geel","Finish":"Satin chrome-plated","Toepassing":"Verlichtingsarmatuur accessoires"},"images":["/catalog/precision-metal/fastener-ra002.jpg"],"documents":[]});
 allProducts.push({"slug":"bevestiger-ra001","name":"Bevestiger RA001","type":"Accessory","category":"CNC, Draaien en Gieten","tags":["CNC","draaien","bevestiger"],"descriptionShort":"CNC precisie-onderdeel voor verlichtingsarmaturen.","descriptionLong":"CNC precisie-onderdeel voor verlichtingsarmaturen. Toepassing: Lighting installation related accessories.","specs":{"Kleur":"Geel","Finish":"Satin chrome-plated","Toepassing":"Verlichtingsarmatuur accessoires"},"images":["/catalog/precision-metal/fastener-ra001.jpg"],"documents":[]});

 // ========== STAALKABELS — Technische Kabels (Velda-specifiek) ==========
 allProducts.push(
  { slug: "staalkabel-rvs-1x19-1mm", name: "RVS Staalkabel 1×19 - 1,00mm", type: "Cable", category: "Staalkabels", tags: ["roestvast staal", "1x19", "stijf"], descriptionShort: "Stijve roestvast stalen kabel, ideaal voor minimale rek.", descriptionLong: "De 1×19 constructie biedt maximale stijfheid. Perfect voor architecturale toepassingen, balustrades en spandraden.", specs: { diameter: "1,00 mm", constructie: "1×19", materiaal: "RVS 316", breekbelasting: "65 kg", werkbelasting: "13 kg", referentie: "K1.1,00.3" }, images: ["/catalog/wire-rope-1x19.svg"], documents: [] },
  { slug: "staalkabel-rvs-7x7-1mm", name: "RVS Staalkabel 7×7 - 1,00mm", type: "Cable", category: "Staalkabels", tags: ["roestvast staal", "7x7", "gemiddeld"], descriptionShort: "Veelzijdige RVS kabel, meest gebruikt in de verlichtingsindustrie.", descriptionLong: "De 7×7 constructie biedt een goede balans tussen flexibiliteit en sterkte.", specs: { diameter: "1,00 mm", constructie: "7×7", materiaal: "RVS 316", breekbelasting: "65 kg", werkbelasting: "13 kg", referentie: "K1.1,00.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-rvs-7x7-1-5mm", name: "RVS Staalkabel 7×7 - 1,50mm", type: "Cable", category: "Staalkabels", tags: ["roestvast staal", "7x7", "gemiddeld"], descriptionShort: "Sterke RVS kabel voor zwaardere ophangingen.", descriptionLong: "Met werkbelasting van 34 kg, geschikt voor zwaardere verlichtingsarmaturen.", specs: { diameter: "1,50 mm", constructie: "7×7", materiaal: "RVS 316", breekbelasting: "174 kg", werkbelasting: "34 kg", referentie: "K1.1,50.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-rvs-7x7-2mm", name: "RVS Staalkabel 7×7 - 2,00mm", type: "Cable", category: "Staalkabels", tags: ["roestvast staal", "7x7", "gemiddeld"], descriptionShort: "Robuuste RVS kabel tot 62 kg werkbelasting.", descriptionLong: "Veel gebruikt in bouw en architectuur voor balustrades, spandraden en veiligheidsinstallaties.", specs: { diameter: "2,00 mm", constructie: "7×7", materiaal: "RVS 316", breekbelasting: "310 kg", werkbelasting: "62 kg", referentie: "K1.2,00.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-rvs-7x7-3mm", name: "RVS Staalkabel 7×7 - 3,00mm", type: "Cable", category: "Staalkabels", tags: ["roestvast staal", "7x7", "gemiddeld"], descriptionShort: "Zware RVS kabel voor industriële toepassingen.", descriptionLong: "Zwaarste standaardkabel met werkbelasting van 140 kg.", specs: { diameter: "3,00 mm", constructie: "7×7", materiaal: "RVS 316", breekbelasting: "698 kg", werkbelasting: "140 kg", referentie: "K1.3,00.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-gegalv-7x7-1-5mm", name: "Gegalvaniseerde Staalkabel 7×7 - 1,50mm", type: "Cable", category: "Staalkabels", tags: ["gegalvaniseerd", "7x7", "gemiddeld"], descriptionShort: "Kosteneffectieve gegalvaniseerde kabel voor binnengebruik.", descriptionLong: "Uitstekende prijs-kwaliteitsverhouding voor droge binnenomgevingen.", specs: { diameter: "1,50 mm", constructie: "7×7", materiaal: "Gegalvaniseerd staal", breekbelasting: "174 kg", werkbelasting: "34 kg", referentie: "K2.1,50.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-gegalv-7x7-2mm", name: "Gegalvaniseerde Staalkabel 7×7 - 2,00mm", type: "Cable", category: "Staalkabels", tags: ["gegalvaniseerd", "7x7", "gemiddeld"], descriptionShort: "Robuuste gegalvaniseerde kabel, budgetvriendelijk.", descriptionLong: "Stevige kabel met goede corrosiebestendigheid voor de meeste binnentoepassingen.", specs: { diameter: "2,00 mm", constructie: "7×7", materiaal: "Gegalvaniseerd staal", breekbelasting: "310 kg", werkbelasting: "62 kg", referentie: "K2.2,00.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-nylon-gecoat-1-5mm", name: "Nylon Gecoate Staalkabel - 1,50/2,00mm", type: "Cable", category: "Staalkabels", tags: ["nylon", "gecoat", "transparant"], descriptionShort: "Transparante nyloncoating beschermt kabel en omgeving.", descriptionLong: "RVS kabel met transparante nyloncoating, voorkomt zwarte vlekken op oppervlakken. Ideaal voor geplafonneerde toepassingen.", specs: { diameter: "1,50/2,00 mm", constructie: "7×7", materiaal: "RVS 316 + Nylon", breekbelasting: "140 kg", werkbelasting: "28 kg", referentie: "K3.1,50.2" }, images: ["/catalog/wire-rope-7x7.svg"], documents: [] },
  { slug: "staalkabel-zwart-gecoat-1-5mm", name: "Zwart Gecoate Staalkabel - 1,50/2,00mm", type: "Cable", category: "Staalkabels", tags: ["zwart", "gecoat", "design"], descriptionShort: "Zwarte coating voor discrete en elegante toepassingen.", descriptionLong: "RVS kabel met zwarte coating, populair in design en architectuur.", specs: { diameter: "1,50/2,00 mm", constructie: "7×7", materiaal: "RVS 316 + Coating", breekbelasting: "140 kg", werkbelasting: "28 kg", referentie: "K4.1,50.2" }, images: ["/catalog/wire-rope-7x19.svg"], documents: [] },
  { slug: "gekleurde-kabels", name: "Gekleurde Staalkabels", type: "Cable", category: "Staalkabels", tags: ["gekleurd", "design", "architectuur"], descriptionShort: "RVS kabels in staal, goud, zwart en wit.", descriptionLong: "Technische excellentie met esthetische flexibiliteit. Ideaal voor architecturale projecten en interieurs.", specs: { kleuren: "Staal, Goud, Zwart, Wit", materiaal: "RVS" }, images: ["/catalog/wire-rope-7x19.svg"], documents: [] },
 );

 // ========== BOWDENKABELS ==========
 allProducts.push(
  { slug: "bowdenkabel-custom", name: "Bowdenkabel op Maat", type: "Cable", category: "Bowdenkabels", tags: ["bowdenkabel", "maatwerk", "OEM"], descriptionShort: "Op maat gemaakte bowdenkabels voor complexe toepassingen.", descriptionLong: "Gespecialiseerd in ingenieuze oplossingen voor complexe technische kabels voor diverse OEM's.", specs: { type: "Bowdenkabel", productie: "Op maat" }, images: ["/catalog/bowdenkabel-op-maat.png"], documents: [] },
  { slug: "throttle-cables", name: "Gaskabels op Maat", type: "Cable", category: "Bowdenkabels", tags: ["gaskabel", "automotive", "maatwerk"], descriptionShort: "Gaskabels voor high-performance motoren en sportwagens.", descriptionLong: "Lage wrijving, hoge duurzaamheid en flexibiliteit. Van klassieke roadsters tot moderne voertuigen.", specs: { type: "Gaskabel", toepassing: "Automotive" }, images: ["/catalog/gaskabel-op-maat.jpeg"], documents: [] },
 );

 await db.insert(products).values(allProducts);

 await db.insert(sectors).values([
  { slug: "industrie", name: "Industriële toepassingen", intro: "Velda Cable Technics is gespecialiseerd in het bedenken en creëren van ingenieuze oplossingen met staalkabels voor de meest uiteenlopende industriële toepassingen. Van manuele bediening tot volledig geautomatiseerde systemen — wij leveren op maat.", useCases: ["Kabels voor manuele bediening", "Kabels voor stopsystemen", "Kabels voor blokkeringssystemen", "Kabels voor automatisatie", "Kabels voor duw- en trek projecten", "Kabels voor grondwerkmachines", "Kabels voor weefmachines", "Kabels voor productiemachines", "Kabels voor verpakkingsmachines", "Kabels voor hijssystemen", "Kabels voor spansystemen", "Kabels voor industriële wasmachines", "Kabels voor de meubelindustrie", "Kabels voor de militaire industrie", "Kabels voor vuurwerk industrie", "Kabels staal/inox in vrac"], galleryImages: [], recommendedProductSlugs: ["bowdenkabel-custom", "draaibare-kabelgrijper", "draaibare-kabelgrijper"], keywords: ["bowdenkabel", "staalkabel", "push-pull", "spankabel", "hijskabel"], flyer: "/flyers/industrie.pdf" },
  { slug: "sport-recreatie", name: "Sport en ontspanning", intro: "Van trampolines tot zeilboten, van kermisattracties tot tennisnetophanging — Velda levert betrouwbare kabels voor de sport- en recreatiesector waar veiligheid en duurzaamheid voorop staan.", useCases: ["Kabels voor zonnebanken", "Kabels voor fietsen en crossfietsen", "Kabels voor scooters en motoren", "Kabels voor kartingwagens", "Kabels voor zeilboten", "Kabels voor parachutes", "Kabels voor trampolines", "Kabels voor kermis/circus attracties", "Kabels voor feestverlichting", "Kabels voor tententechnologie", "Kabels voor tennisnet ophanging", "Kabels voor jachtstroppen"], galleryImages: [], recommendedProductSlugs: ["draaibare-kabelgrijper-met-schroef", "bowdenkabel-custom", "draaibare-kabelgrijper"], keywords: ["bowdenkabel", "remkabel", "gaskabel", "veiligheidskabel", "spankabel"], flyer: "/flyers/sport-recreatie.pdf" },
  { slug: "verlichting-interieur", name: "Verlichting en interieur", intro: "Velda is uitgegroeid tot een van de belangrijkste spelers in de Europese verlichtingsindustrie. Wij leveren volledig geassembleerde ophangkits in gepersonaliseerde verpakking voor verlichting, interieurprojecten en winkelinrichting.", useCases: ["Kabels voor verlichting ophanging", "Kabels voor trapleuningen", "Kabels voor winkelinrichting", "Kabels voor plafond ophanging", "Kabels voor kaderophanging", "Kabels voor paneelophanging", "Kabels voor richtingaanwijzing", "Kabels voor voetmatten", "Kabelsystemen voor klimplanten", "Kabels voor interieurprojecten", "Kabelsystemen voor expokasten", "Kabels voor buislamp ophanging"], galleryImages: [], recommendedProductSlugs: ["looping-gripper-lg-001zn", "draaibare-kabelgrijper", "verlichtings-ophangkit-sk053", "plafondbevestiging-t-profiel-ca028"], keywords: ["ophangkabel", "gripper", "looping", "ophangkit", "kabelgrijper", "plafond", "verlichting"], flyer: "/flyers/verlichting-interieur.pdf" },
  { slug: "landbouw", name: "Land- en tuinbouw", intro: "De land- en tuinbouw stelt hoge eisen aan kabels: robuust, weerbestendig en betrouwbaar. Velda levert kabels voor tractoren, maaimachines, grondfreesmachines en meetkabels voor grondboringen.", useCases: ["Kabels voor tractoren", "Kabels voor grasmachines", "Kabels voor maaimachines", "Kabels voor dorsmachines", "Kabels voor plukmachines", "Kabels voor rooimachines", "Kabels voor grondfreesmachines", "Kabels voor horticultuurmachines", "Kabels met pushpull toepassing", "Meetkabels voor grondboringen", "Meetkabels voor aanplanting", "Kabels voor dierenstalling", "Sleep en trekkabels"], galleryImages: [], recommendedProductSlugs: ["bowdenkabel-custom", "draaibare-kabelgrijper"], keywords: ["bowdenkabel", "trekkabel", "push-pull", "gaskabel"], flyer: "/flyers/landbouw.pdf" },
  { slug: "medisch", name: "Paramedisch", intro: "In de medische en paramedische sector zijn betrouwbaarheid en precisie van levensbelang. Velda levert kabels voor ziekenbedden, operatietafels, tandartsstoelen, fitnesstoestellen en rolstoelen.", useCases: ["Kabels voor ziekenbedden", "Kabels voor tandartsstoelen", "Kabels voor operatietafels", "Kabels voor fitnesstoestellen", "Kabels voor rolstoelen"], galleryImages: [], recommendedProductSlugs: ["bowdenkabel-custom", "draaibare-kabelgrijper"], keywords: ["bowdenkabel", "veiligheidskabel", "push-pull", "remkabel"], flyer: "/flyers/paramedisch.pdf" },
  { slug: "signalisatie-shopfitting", name: "Signalisatie en promotie", intro: "Elegante ophangoplossingen voor signalisatie, displays, affiches en winkelinrichting. Velda levert complete kabelsystemen voor professionele presentaties.", useCases: ["Kabels voor ophangpanelen", "Kabels voor koordgeleiders", "Kabels voor displays", "Kabels voor affiches", "Kabels voor winkelinrichting"], galleryImages: [], recommendedProductSlugs: ["display-accessoire-ds021", "display-accessoire-ds014", "looping-gripper-lg-001zn"], keywords: ["display", "ophangkabel", "kabelgrijper", "gripper", "signalisatie"], flyer: "/flyers/signalisatie.pdf" },
  { slug: "automotive", name: "Automotive industrie", intro: "Velda levert op maat gemaakte kabeloplossingen voor de automotive industrie: van aanhangwagens en motorbediening tot autozetels, spiegelbediening en temperatuurregeling.", useCases: ["Kabels voor aanhangwagens", "Kabels voor motorbediening", "Kabels voor rembedieningen", "Kabels voor deur/koffer bediening", "Kabels voor autozetels", "Kabels voor deurbediening", "Kabels voor spiegelbediening", "Kabels voor temperatuurregeling", "Speedo en tachokabels", "Sleep en startkabels", "Kabels voor campingwagens", "Veiligheidskabels allerlei", "Kabels voor trailers", "Kabels voor de scheepvaart", "Fijne staalkabels in vrac"], galleryImages: [], recommendedProductSlugs: ["bowdenkabel-custom", "throttle-cables"], keywords: ["bowdenkabel", "gaskabel", "remkabel", "veiligheidskabel", "throttle"], flyer: "/flyers/automotive.pdf" },
  { slug: "veiligheid", name: "Veiligheid", intro: "Veiligheidskabels vormen een cruciaal onderdeel van beveiligingssystemen. Velda levert kabels voor computerbeveiliging, antidiefstal, podiumlichten anti-val en ophanging van geluidsboxen.", useCases: ["Kabels voor computerbeveiliging", "Kabels voor antidiefstal", "Kabels voor gokautomaten", "Kabels voor podiumlichten anti-val", "Kabels voor ophanging geluidsboxen", "Kabels voor showspots anti-val"], galleryImages: [], recommendedProductSlugs: ["kabelgrijper-met-m8-schroefdraad", "draaibare-kabelgrijper"], keywords: ["veiligheidskabel", "kabelgrijper", "anti-val", "ophangkabel"], flyer: "/flyers/veiligheid.pdf" },
  { slug: "bouw", name: "Bouw en architectuur", intro: "Binnen de bouwsector zijn veel specifieke staalkabels nodig. Velda Cable Technics levert kabels voor tuimelramen, badkamersanitair, trapleuningen, rolluiken, poorten en luifels/zonneweringen.", useCases: ["Kabels voor tuimelramen", "Kabels voor badkamersanitair", "Kabels voor trapleuningen", "Kabels voor rolluiken", "Kabels voor poorten", "Kabels voor luifels/zonneweringen"], galleryImages: [], recommendedProductSlugs: ["draaibare-kabelgrijper", "bowdenkabel-custom"], keywords: ["bowdenkabel", "staalkabel", "spankabel", "balustrade", "trapleuning"], flyer: "/flyers/bouw.pdf" },
 ]);

 await db.insert(jobs).values([
  {
    slug: "sales-medewerker",
    title: "Sales Medewerker Binnendienst",
    description: "Als Sales Medewerker Binnendienst bij Velda Cable Technics ben je het eerste aanspreekpunt voor onze klanten. Je verwerkt offertes, beheert orders en onderhoudt klantrelaties. Je werkt nauw samen met het productieteam om leveringen te coördineren.",
    requirements: ["Ervaring in B2B sales of klantenservice", "Uitstekende communicatieve vaardigheden in het Nederlands", "Kennis van MS Office en ERP-systemen", "Technische affiniteit is een plus", "Teamspeler met zelfstandig werkvermogen"],
    offerings: ["Competitief salaris met bonusregeling", "Vast contract na proefperiode", "Opleidingsmogelijkheden", "Aangename werkomgeving in familiebedrijf", "Maaltijdcheques en hospitalisatieverzekering"],
    location: "Ronse",
    type: "voltijds",
    active: true,
  },
  {
    slug: "productie-medewerker",
    title: "Productie Medewerker Kabelassemblage",
    description: "Als Productie Medewerker sta je in voor de assemblage van staalkabels en ophangingssystemen. Je werkt met precisie-apparatuur en zorgt voor de kwaliteitscontrole van afgewerkte producten. Je draagt bij aan de continue verbetering van onze productieprocessen.",
    requirements: ["Technische achtergrond of ervaring in productie", "Nauwkeurig en kwaliteitsbewust", "Fysiek in goede conditie", "Bereidheid tot ploegwerk", "Kennis van kwaliteitsnormen is een plus"],
    offerings: ["Competitief uurloon met ploegenpremie", "Vast contract", "Gratis werkkleding en gereedschap", "Opleiding on-the-job", "Maaltijdcheques"],
    location: "Ronse",
    type: "voltijds",
    active: true,
  },
  {
    slug: "stagiair-engineering",
    title: "Stagiair Engineering & Productontwikkeling",
    description: "Ben je een ambitieuze student en wil je hands-on ervaring opdoen in de wereld van staalkabelassemblage? Als stagiair werk je mee aan productontwikkeling, test je nieuwe materialen en help je bij de optimalisatie van bestaande producten.",
    requirements: ["Student industrieel ingenieur of elektromechanica", "Interesse in materiaalwetenschap en productietechnologie", "Analytisch denkvermogen", "Goede kennis van Nederlands en/of Engels", "Motivatie om te leren"],
    offerings: ["Relevante werkervaring in een internationaal bedrijf", "Begeleiding door ervaren ingenieurs", "Kans op vaste aanstelling na stage", "Flexibele stage-uren", "Vergoeding voor verplaatsingskosten"],
    location: "Ronse",
    type: "stage",
    active: true,
  },
 ]);

 console.log(`Database seeded successfully! ${allProducts.length} products created.`);
}
